apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-server
  labels:
    app: ad-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-server
  template:
    metadata:
      name: ad-server
      labels:
        app: ad-server
    spec:
      containers:
        - name: ad-server
          image: ghcr.io/eason0729/ad-server/backend:staging
          imagePullPolicy: IfNotPresent
          env:
          - name: READ_HOST
            value: postgres-ro.default.svc.cluster.local
          - name: WRITE_HIST
            value: postgres-rw.default.svc.cluster.local
          - name: PASSWORD
            valueFrom:
              secretKeyRef: 
                name: postgres-app
                key: password
          ports:
            - containerPort: 3000
              name: web
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ad-server
  labels:
    app: ad-server
spec:
  selector:
    app: ad-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ad-server
  annotations:
    kubernetes.io/ingress.class: public
spec:
  rules:
    - host: ad-server.local
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: ad-server
              port:
                number: 3000
