apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-server
  labels:
    app: ad-server
  annotations:
    sidecar.opentelemetry.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-server
  template:
    metadata:
      name: ad-server
      labels:
        app: ad-server
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
        - name: ad-server
          image: ghcr.io/eason0729/ad-server/backend:staging
          imagePullPolicy: IfNotPresent
          env:
          - name: OTEL_TRACES_SAMPLER
            value: "0.05"
          - name: READ_HOST
            value: postgres-ro.default.svc.cluster.local
          - name: WRITE_HOST
            value: postgres-rw.default.svc.cluster.local
          - name: PASSWORD
            valueFrom:
              secretKeyRef: 
                name: postgres-app
                key: password
          ports:
            - containerPort: 3000
              name: web
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ad-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ad-server
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40
---
apiVersion: v1
kind: Service
metadata:
  name: ad-server
  labels:
    app: ad-server
spec:
  selector:
    app: ad-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ad-server
  annotations:
    spec.ingressClassName: public
spec:
  rules:
    - host: ad-server.local
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: ad-server
              port:
                number: 3000
