# https://www.enterprisedb.com/blog/Trying-Out-CloudNative-PG-Novice-Kubernetes-World
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 2
  storage:
    size: 4Gi
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
