apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 5
  replicationSlots:
    updateInterval: 60
  storage:
    size: 4Gi
  bootstrap:
    initdb:
      database: ad-server
      owner: eason
      
